version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - uxtracker.web
      - uxtracker.api
  
  uxtracker.api:
    image: uxtracker.api
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: uxtracker.api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Database__ConnectionString=${DATABASE__CONNECTIONSTRING}
      - SendGrid__ApiKey=${SENDGRID__APIKEY}
      - JwtPrivateKey=${JWT_PRIVATE_KEY}
      - DefaultFromEmail=${DEFAULT_FROM_EMAIL}
      - CorsPolicyName=${CORS_POLICY_NAME}
      - PasswordSaltKey=${PASSWORD_SALT_KEY}
      - FrontendUrl=${FRONTEND_URL}
      - BackendUrl=${BACKEND_URL}
    volumes:
      - ./data/images:/app/wwwroot/ConsentTerms
    ports:
      - "8080:8080"
    restart: always


  uxtracker.web:
    image: uxtracker.web
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: uxtracker.web
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - FrontendUrl=${FRONTEND_URL}
      - BackendUrl=${BACKEND_URL}
    ports:
      - "8081:8081"
    restart: always
