FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

# RUN apt install certbot -y python3-certbot-nginx -y
# RUN apk add --no-cache ca-certificates

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]