services:
  uxtracker.api:
    image: uxtracker.api
    container_name: ux-tracker-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Database__ConnectionString=${DATABASE__CONNECTIONSTRING}
      - SendGrid__ApiKey=${SENDGRID__APIKEY}
      - JwtPrivateKey=${JWT_PRIVATE_KEY}
      - DefaultFromEmail=${DEFAULT_FROM_EMAIL}
      - CorsPolicyName=${CORS_POLICY_NAME}
      - PasswordSaltKey=${PASSWORD_SALT_KEY}
      - FrontendUrl=${FRONTEND_URL}
      - BackendUrl=${BACKEND_URL}
    volumes:
      - ./data/images:/app/wwwroot/
    ports:
      - "8080:8080"
  
  uxtracker.web:
    image: uxtracker.web
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - FrontendUrl=${FRONTEND_URL}
      - BackendUrl=${BACKEND_URL}
    volumes:
      - ./data/images:/app/wwwroot/
    ports:
      - "80:80"
    depends_on:
      - uxtracker.api
      
#  working_dir: /app
        
volumes:
  uxtracker_data: